//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyObject implements runtime.Object.
func (in *TxTokenConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy creates a deep copy of TxTokenConfig.
func (in *TxTokenConfig) DeepCopy() *TxTokenConfig {
	if in == nil {
		return nil
	}
	out := new(TxTokenConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into another TxTokenConfig.
func (in *TxTokenConfig) DeepCopyInto(out *TxTokenConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TxTokenConfigSpec) DeepCopyInto(out *TxTokenConfigSpec) {
	*out = *in
	if in.SubjectTokens != nil {
		out.SubjectTokens = make([]SubjectTokenAuthenticator, len(in.SubjectTokens))
		for i := range in.SubjectTokens {
			in.SubjectTokens[i].DeepCopyInto(&out.SubjectTokens[i])
		}
	}
}

func (in *SubjectTokenAuthenticator) DeepCopyInto(out *SubjectTokenAuthenticator) {
	*out = *in
	in.Issuer.DeepCopyInto(&out.Issuer)
	if in.ClaimValidationRules != nil {
		out.ClaimValidationRules = make([]ClaimValidationRule, len(in.ClaimValidationRules))
		copy(out.ClaimValidationRules, in.ClaimValidationRules)
	}
	in.ClaimMappings.DeepCopyInto(&out.ClaimMappings)
}

func (in *IssuerConfig) DeepCopyInto(out *IssuerConfig) {
	*out = *in
	if in.Audiences != nil {
		out.Audiences = make([]string, len(in.Audiences))
		copy(out.Audiences, in.Audiences)
	}
}

func (in *ClaimMappings) DeepCopyInto(out *ClaimMappings) {
	*out = *in
	if in.Extra != nil {
		out.Extra = make([]ExtraMapping, len(in.Extra))
		copy(out.Extra, in.Extra)
	}
}

func (in *TxTokenConfigStatus) DeepCopyInto(out *TxTokenConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in.Conditions = make([]metav1Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

// DeepCopyObject implements runtime.Object.
func (in *TxTokenConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TxTokenConfigList) DeepCopy() *TxTokenConfigList {
	if in == nil {
		return nil
	}
	out := new(TxTokenConfigList)
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TxTokenConfig, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
	return out
}

// --- TransactionType ---

func (in *TransactionType) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TransactionType) DeepCopy() *TransactionType {
	if in == nil {
		return nil
	}
	out := new(TransactionType)
	in.DeepCopyInto(out)
	return out
}

func (in *TransactionType) DeepCopyInto(out *TransactionType) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TransactionTypeSpec) DeepCopyInto(out *TransactionTypeSpec) {
	*out = *in
	if in.TctxMapping != nil {
		out.TctxMapping = make(map[string]TctxFieldMapping, len(in.TctxMapping))
		for k, v := range in.TctxMapping {
			out.TctxMapping[k] = v
		}
	}
	if in.TctxEnrichments != nil {
		out.TctxEnrichments = make([]TctxEnrichment, len(in.TctxEnrichments))
		copy(out.TctxEnrichments, in.TctxEnrichments)
	}
	if in.RctxFields != nil {
		out.RctxFields = make([]string, len(in.RctxFields))
		copy(out.RctxFields, in.RctxFields)
	}
}

func (in *TransactionTypeStatus) DeepCopyInto(out *TransactionTypeStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
	if in.ProducedTctxFields != nil {
		out.ProducedTctxFields = make([]string, len(in.ProducedTctxFields))
		copy(out.ProducedTctxFields, in.ProducedTctxFields)
	}
}

func (in *TransactionTypeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TransactionTypeList) DeepCopy() *TransactionTypeList {
	if in == nil {
		return nil
	}
	out := new(TransactionTypeList)
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TransactionType, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
	return out
}

// --- ServiceTokenRequirement ---

func (in *ServiceTokenRequirement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ServiceTokenRequirement) DeepCopy() *ServiceTokenRequirement {
	if in == nil {
		return nil
	}
	out := new(ServiceTokenRequirement)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceTokenRequirement) DeepCopyInto(out *ServiceTokenRequirement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ServiceTokenRequirementSpec) DeepCopyInto(out *ServiceTokenRequirementSpec) {
	*out = *in
	if in.ExcludedEndpoints != nil {
		out.ExcludedEndpoints = make([]EndpointSpec, len(in.ExcludedEndpoints))
		copy(out.ExcludedEndpoints, in.ExcludedEndpoints)
	}
	in.Verification.DeepCopyInto(&out.Verification)
}

func (in *VerificationSpec) DeepCopyInto(out *VerificationSpec) {
	*out = *in
	if in.RequiredTctxFields != nil {
		out.RequiredTctxFields = make([]string, len(in.RequiredTctxFields))
		copy(out.RequiredTctxFields, in.RequiredTctxFields)
	}
	if in.Rules != nil {
		out.Rules = make([]VerificationRule, len(in.Rules))
		copy(out.Rules, in.Rules)
	}
}

func (in *ServiceTokenRequirementStatus) DeepCopyInto(out *ServiceTokenRequirementStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

func (in *ServiceTokenRequirementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ServiceTokenRequirementList) DeepCopy() *ServiceTokenRequirementList {
	if in == nil {
		return nil
	}
	out := new(ServiceTokenRequirementList)
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ServiceTokenRequirement, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
	return out
}

// --- TokenPolicy ---

func (in *TokenPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TokenPolicy) DeepCopy() *TokenPolicy {
	if in == nil {
		return nil
	}
	out := new(TokenPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *TokenPolicy) DeepCopyInto(out *TokenPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TokenPolicySpec) DeepCopyInto(out *TokenPolicySpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		out.TargetNamespaces = in.TargetNamespaces.DeepCopy()
	}
	if in.AuthorizedTransactionNamespaces != nil {
		out.AuthorizedTransactionNamespaces = in.AuthorizedTransactionNamespaces.DeepCopy()
	}
	if in.AuthorizedRequesters != nil {
		out.AuthorizedRequesters = make([]RequesterRule, len(in.AuthorizedRequesters))
		for i := range in.AuthorizedRequesters {
			in.AuthorizedRequesters[i].DeepCopyInto(&out.AuthorizedRequesters[i])
		}
	}
	in.Constraints.DeepCopyInto(&out.Constraints)
	if in.IssuanceRules != nil {
		out.IssuanceRules = make([]IssuanceRule, len(in.IssuanceRules))
		copy(out.IssuanceRules, in.IssuanceRules)
	}
	if in.AccessEvaluationWebhook != nil {
		out.AccessEvaluationWebhook = new(WebhookConfig)
		*out.AccessEvaluationWebhook = *in.AccessEvaluationWebhook
	}
}

func (in *NamespaceSelector) DeepCopy() *NamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelector)
	if in.MatchNames != nil {
		out.MatchNames = make([]string, len(in.MatchNames))
		copy(out.MatchNames, in.MatchNames)
	}
	if in.MatchLabels != nil {
		out.MatchLabels = make(map[string]string, len(in.MatchLabels))
		for k, v := range in.MatchLabels {
			out.MatchLabels[k] = v
		}
	}
	return out
}

func (in *RequesterRule) DeepCopyInto(out *RequesterRule) {
	*out = *in
	if in.NamespaceSelector != nil {
		out.NamespaceSelector = in.NamespaceSelector.DeepCopy()
	}
	if in.ServiceAccountNames != nil {
		out.ServiceAccountNames = make([]string, len(in.ServiceAccountNames))
		copy(out.ServiceAccountNames, in.ServiceAccountNames)
	}
}

func (in *PolicyConstraints) DeepCopyInto(out *PolicyConstraints) {
	*out = *in
	if in.MandatoryTctxFields != nil {
		out.MandatoryTctxFields = make([]string, len(in.MandatoryTctxFields))
		copy(out.MandatoryTctxFields, in.MandatoryTctxFields)
	}
	if in.MandatoryRctxFields != nil {
		out.MandatoryRctxFields = make([]string, len(in.MandatoryRctxFields))
		copy(out.MandatoryRctxFields, in.MandatoryRctxFields)
	}
	if in.DisallowedEnrichers != nil {
		out.DisallowedEnrichers = make([]string, len(in.DisallowedEnrichers))
		copy(out.DisallowedEnrichers, in.DisallowedEnrichers)
	}
}

func (in *TokenPolicyStatus) DeepCopyInto(out *TokenPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}

func (in *TokenPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TokenPolicyList) DeepCopy() *TokenPolicyList {
	if in == nil {
		return nil
	}
	out := new(TokenPolicyList)
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TokenPolicy, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
	return out
}

// type alias for readability in deep copy methods
type metav1Condition = metav1.Condition
