apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: kontxt
    app.kubernetes.io/part-of: kontxt
    {{- if .Values.istio.enabled }}
    istio.io/dataplane-mode: ambient
    {{- end }}
